#!/bin/bash

if [ -z $ANSIBLE_IMAGE ];then
  ANSIBLE_IMAGE=williamyeh/ansible:centos7
fi

if [ -z $ANSIBLE_DOCKER_OPTS ];then
  ANSIBLE_DOCKER_OPTS="  "
fi

# -v ansible:/root/.ssh/

docker run --tty --rm -it -v $PWD:/ansible -w /ansible $ANSIBLE_DOCKER_OPTS $ANSIBLE_IMAGE ansible-playbook $@
