#!/bin/bash

ID=$1

CMD=bash

if [ ! -z $2 ]
then
  CMD=$2
fi

if [ ! -z "$(docker images -aq | grep $ID)" ]
then

  echo "it's an image"
  
  docker run --rm -it $ID $CMD

  exit $?
fi

if [ ! -z "$(docker ps -aq | grep $ID)" ]
then

  echo "it's a container"

  docker exec -it $ID $CMD

  exit $?

else

  docker run --rm -it $ID $CMD
  
fi
