#!/bin/bash

source $(dirname $0)/commons.sh

BUILDER_APPLI_NAME=""

BUILDER_PLUGINS_DIR=$(dirname $0)/plugins

BUILDER_WORKSPACE=$(pwd)
BUILDER_DELETE_VOLUME="true"
BUILDER_FILE="$BUILDER_WORKSPACE/Builderfile"

BUILDER_TARGET="$BUILDER_WORKSPACE/target"

echo "BUILDER_PLUGINS_DIR   $BUILDER_PLUGINS_DIR"
echo "BUILDER_WORKSPACE     $BUILDER_WORKSPACE"
echo "BUILDER_TARGET        $BUILDER_TARGET"
echo "BUILDER_FILE          $BUILDER_FILE"

if [ ! -e $BUILDER_FILE ]
then

  echo "$BUILDER_FILE not found"
  exit 1

fi

## Plugins loading

for plugin in $BUILDER_PLUGINS_DIR/*.sh
do
  RUN source $plugin
done

## Builderfile loading

source $BUILDER_FILE

BUILDER_VOLUME="Build_"${BUILDER_APPLI_NAME,,} # lowercase
BUILDER_VOLUME=${BUILDER_VOLUME// /_}

echo "BUILDER_VOLUME        $BUILDER_VOLUME"
echo "BUILDER_DELETE_VOLUME $BUILDER_DELETE_VOLUME"

## Clean volume before building

if [ "$BUILDER_DELETE_VOLUME" == "true" ]
then
  echo "Delete build volume $BUILDER_VOLUME"
  docker volume rm  $BUILDER_VOLUME
fi

## Create docker volume for building

docker volume create $BUILDER_VOLUME

## run build method from Builderfile

build









