#!/bin/bash

ID=$1

if [ ! -z $(docker images -aq | grep $ID) ]
then

  echo "it's an image"
  
  docker run --rm -it $ID sh -cl "ls /$2"

fi

if [ ! -z $(docker ps -aq | grep $ID) ]
then

  echo "it's a container"

  docker exec -it $ID sh -cl "ls /$2"

fi

if [ ! -z $(docker volume ls -q | grep $ID) ]
then

  echo "it's a volume"

  docker run --rm -it -v $ID:/target busybox sh -cl "ls /target/$2"

fi
