#!/bin/bash

CONTAINER="$1"
FILE="$2"
#OPTIONS="$3"

OPTIONS=" -U postgres -d postgres " 

IMAGE=$(docker inspect --format='{{.Image}}' $CONTAINER)

docker run --rm -it -v $(pwd):/tmp/ --link $CONTAINER:CIBLE $IMAGE bash -cl "psql $OPTIONS -h CIBLE -p 5432 -q -f /tmp/$(basename $FILE) "
