#!/bin/bash
set -e

IMAGE="$1"
FILE="$2"
OPTIONS="$3"

#OPTIONS=" -U cdm -d cdm "

#IMAGE=$(docker inspect --format='{{.Image}}' $CONTAINER)

docker run --rm -it  -v $(pwd):/work/ -e PGPASSWORD=$PGPASSWORD $IMAGE bash -cl "pg_restore $OPTIONS /work/$FILE "
