#!/bin/bash
set -e

CONTAINER="$1"
QUERY="$2"
OPTIONS="$3"

#OPTIONS=" -U postgres -d postgres " 

IMAGE=$(docker inspect --format='{{.Image}}' $CONTAINER)

docker run --rm -it --link="$CONTAINER"  -v $(pwd):/work/ -e PGPASSWORD=$PGPASSWORD $IMAGE bash -cl "echo $QUERY | psql $OPTIONS -h $CONTAINER -p 5432 -q "
