#!/bin/bash

CONTAINER="$1"
FILE="$2"
OPTIONS="$3"



IMAGE=$(docker inspect --format='{{.Image}}' $CONTAINER)

docker run --rm -it --network="container:$CONTAINER" -v $(pwd):/tmp/ $IMAGE bash -cl "pg_dump $OPTIONS -h $CONTAINER -p 5432 > /tmp/$(basename $FILE) "
