#!/bin/bash

IMAGE="$1"
FILE="$2"
OPTIONS="$3"

#OPTIONS=" -U postgres -d cdm -n cdm -h 10.85.209.174 -p 15432 --format=tar "

docker run --rm -it -v $(pwd):/tmp/ $IMAGE bash -cl "pg_dump $OPTIONS > /tmp/$(basename $FILE) "
