#!/bin/bash

source $(dirname $0)/commons.sh

HERE=$(dirname $0)

DOCKER_IMAGE="test/docker-go-alpine"

go(){
   local CMD="docker run --rm -it -v $HERE/pipe:/pipe -v $PWD/Pipefile:/pipe/Pipefile.go -v /var/run/docker.sock:/var/run/docker.sock -w /pipe $DOCKER_IMAGE go run Pipefile.go hello.go"
   echo $CMD
   $CMD
}

RUN go
