#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Usage: $0 CMD NAME [FILE]"
	echo " - browse NAME"
	echo " - clear NAME -f"
	echo " - export NAME FILE"
	echo " - import NAME FILE"
	echo " - ls NAME"
  echo " - size [NAME]"
	exit 1
fi

ARG=$1
VOLUME=$2
FILE=$3


if [ $ARG = "clear" ]
then
	read -p "All data will be lost for '$VOLUME' (Y/n): " answer

	if [ $answer == "Y" ]
	then
		docker volume rm $VOLUME
		docker volume create --name $VOLUME
	fi
fi

if [ $ARG = "browse" ]
then

  if [ -z $VOLUME ]
  then
    echo "volume not specified"
  else
	  docker run --rm -it -v $VOLUME:/volume -w /volume busybox sh
  fi
fi

if [ $ARG = "export" ]
then

  if [ -z $VOLUME ] || [ -z $FILE ]
  then
	  echo "volume or file not specified"
  else
    docker run --rm -it -v $VOLUME:/source -v $(pwd):/target busybox sh -cl "cd /source && tar cvfz /target/$FILE * "
  fi
fi

if [ $ARG = "import" ]
then

  if [ -z $VOLUME ] || [ -z $FILE ]
  then
	  echo "volume or file not specified"
  else
  
    ./$0 clear $VOLUME

    docker run --rm -it -v $VOLUME:/target -v $(pwd):/source busybox sh -cl "cd /target && tar xvfz /source/$FILE "
  fi
fi

if [ $ARG = "ls" ]
then

  if [ -z $VOLUME ]
  then
	  echo "volume or file not specified"
  else
    docker run --rm -it -v $VOLUME:/source busybox sh -cl "ls /source"
  fi
fi

if [ $ARG = "size" ]
then

  if [ -z $VOLUME ]
  then
	  echo "volume not specified"
  else
    docker run --rm -it -v $VOLUME:/source busybox sh -cl "cd /source && du -sh "
  fi
fi
